### ISSUE TITLE
Move development to shikiji

### ISSUE THREAD

**Issue by pi0** [unjs/shiki-es#15]
I think we might move the development of this project [antfu/shikiji](https://github.com/antfu/shikiji).

@antfu How do you think if we can support base64 inlined dist as well in shikiji as a separate dist variant so we can move projects to one?

**Comment by antfu** [comment]
What do you mean specifically?

**Comment by pi0** [comment]
(send DM)

**Comment by antfu** [comment]
By default, `shikiji` use the based64 encoded WASM, so it works as pure ESM without any assets loading.

It also ships a .wasm file, so optionally, users can use native wasm (CF requires this, for example)

I think we could deprecate this project and move to `shikiji`. One thing to note is that `shikiji` is not a 1:1 drop-in replacement, but I also made a `shikiji-compact` with 95% of API alignment: https://github.com/antfu/shikiji#breaking-changes-from-shiki
https://github.com/nuxt-modules/mdc, Slidev, Nuxt DevTools already migrated to shikiji, which I think is a sign indicates that `shikiji` is quite stable now
