### ISSUE TITLE
big delay

### ISSUE THREAD

**Issue by mak33v** [unjs/shiki-es#3]
Greetings. I have a code output delay of about 3-5 seconds, what could be the problem?

`const highlighter = await getHighlighter({ theme: 'github-dark' })`
`elem.innerHTML = highlighter.codeToHtml('console.log(123)', { lang: 'js' }) // log after delay 3-5 sec`

**Comment by alvarosabu** [comment]
Possibly related to Blocked https://github.com/unjs/shiki-es/issues/4 specially if you are having multiple snippets

**Comment by Mokkapps** [comment]
Add `{ includeExplanation: false }` as option to `codeToHtml`, it improves the performance a lot!

**Comment by acidjazz** [comment]
this made a massive difference for me, maybe document it?

**Comment by pi0** [comment]
Please move to https://github.com/antfu/shikiji
