### ISSUE TITLE
Too many language JSON fetching when having multiple code snippets

### ISSUE THREAD

**Issue by alvarosabu** [unjs/shiki-es#4]
## Description

When using Shiki-es on multiple code blocks (consider a blog post with several snippets) the language.json are triggered multiple times

## Repro 
1. Check the network tab on https://stackblitz.com/edit/vitejs-vite-acb5cw?file=src/App.vue

<img width="1253" alt="Screenshot 2022-09-06 at 12 12 10" src="https://user-images.githubusercontent.com/4699008/188610095-f315e427-9d38-49a0-b3f9-b08ce517168b.png">

## Solution desired

Don't fetch language JSON files if they are already there.

**Comment by alvarosabu** [comment]
Investigating a little bit more seems like a general problem from Shiki itself https://github.com/shikijs/shiki/issues/306 you can leverage the impact by passing an array of wanted languages, but they still have an issue caching language JSON files

**Comment by 1714080902120** [comment]
![image](https://github.com/unjs/shiki-es/assets/48143943/0222dce5-5b42-47fb-8545-8be4b8782544)
can it be splited into `vue template` or just add a new json `vue template` ?

**Comment by pi0** [comment]
Please move to https://github.com/antfu/shikiji
